models:
  - name: fb_aws_llm
    api_url: https://api-inference.huggingface.co/models/meta-llama/Llama-2-7b-chat-hf
    api_token: ${HF_API_TOKEN}
    max_tokens: 1000
    temperature: 1
    top_p: 0.1
    top_k: 0
    do_sample: False
    return_full_text: False
    frequency_penalty: 0
    presence_penalty: 0

  - name: zephyr-7b-beta
    api_url: https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-beta
    api_token: ${HF_API_TOKEN}
    max_tokens: 1000
    temperature: 1
    top_p: 0.1
    top_k: 0
    do_sample: False
    return_full_text: False
    frequency_penalty: 0
    presence_penalty: 0

  - name: Llama-2-7b-chat-hf
    api_url: https://api-inference.huggingface.co/models/meta-llama/Llama-2-7b-chat-hf
    api_token: ${HF_API_TOKEN}
    max_tokens: 1000
    temperature: 1
    top_p: 0.1
    top_k: 0
    do_sample: False
    return_full_text: False
    frequency_penalty: 0
    presence_penalty: 0
  
